---
- name: Configure static network (eth0)
  ansible.builtin.copy:
    dest: /etc/netplan/01-lan.yaml
    content: |
      network:
        version: 2
        ethernets:
          eth0:
            dhcp4: no
            addresses:
              - 192.168.0.3/24
            routes:
              - to: default
                via: 192.168.0.1
            nameservers:
              addresses:
                - 1.1.1.1
                - 8.8.8.8
  notify: apply netplan