---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: dist

- name: Install common packages
  ansible.builtin.apt:
    name:
      - curl
      - git
      - vim
      - htop
      - unzip
      - net-tools
      - dnsutils
      - jq
    state: present

- name: Set timezone
  community.general.timezone:
    name: America/Los_Angeles